name: Deploy Docs Folder

on:
  push:
    paths:
      - 'docs/**'
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy docs folder via rsync
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avz --delete
          path: docs/
          remote_path: ${{ secrets.SSH_TARGET_DOCS }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: 22022
